# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8b300705eab2174559012e02617f2003c00558e5a90c367d2abc2bc474d882e5dfbe6634e2b9fc5e1d48fd18de932955630a75f773f6c6befba7a10af351323

test:
  secret_key_base: 65860e03f96c06b0ef143dd1cc2fa0ae08d6a3898a0ec92c2ae39abc30be0b1cbd3eab65c97fbc91bb4dc413ee0d66534ce63330a5a6587b3822ee41d5ed6241

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
